//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 21-10-2015 19:33:23
namespace Match3
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        /// <summary> Path to Content/Tiles.spritesheet </summary>
        public const string Tiles_spritesheet = "Content/Tiles.spritesheet";
        
        /// <summary> Texture names from spritesheet Content/Tiles.spritesheet </summary>
        public struct Tiles_spritesheet_TextureName
        {
            
            public const string black = "black";
            
            public const string blue = "blue";
            
            public const string green = "green";
            
            public const string red = "red";
            
            public const string yellow = "yellow";
        }
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/black.png </summary>
            public const string black_png = "Content/Assets/black.png";
            
            /// <summary> Path to Content/Assets/blue.png </summary>
            public const string blue_png = "Content/Assets/blue.png";
            
            /// <summary> Path to Content/Assets/green.png </summary>
            public const string green_png = "Content/Assets/green.png";
            
            /// <summary> Path to Content/Assets/red.png </summary>
            public const string red_png = "Content/Assets/red.png";
            
            /// <summary> Path to Content/Assets/yellow.png </summary>
            public const string yellow_png = "Content/Assets/yellow.png";
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MainMenuScene.wscene </summary>
            public const string MainMenuScene = "Content/Scenes/MainMenuScene.wscene";
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
